// core/src/main/resources/vue/views/patient-list.vue
<template id="patient-list">
    <doctor-layout>
        <h4 class="ml-4">Patient List</h4>
        <div class="col-12">
            <table class="table" this="table">
                <thead>
                <th scope="col" class="text-left">
                    Name
                </th>
                <th scope="col" class="text-center">
                    Number
                </th>
                <th scope="col" class="text-right">
                    Profile
                </th>
                </thead>
                <tbody>
                <template v-for="(patient,index) in patients" :key="index">
                    <patient-list-item  v-bind:patient="patient"></patient-list-item>
                </template>
                </tbody>
            </table>
        </div>
    </doctor-layout>
</template>
<script>
    Vue.component("patient-list", {
        template: "#patient-list",
        data: () => ({
                patients: []
            }),
        created() {
            window.apiService.getPatients().then(json => {
                this.patients = json
            });
        }

    })

</script>

// react-mobile-site/src/views/Patient-List/PatientList.js
import React, { Component } from "react";
import Navbar from "../../components/Navbar";
import { Link } from "react-router-dom";
import * as api from "../../utils/api";

class PatientList extends Component {
  constructor(props) {
    super(props);
    this.state = { patients: [] };
    this.getPatientList = this.getPatientList.bind(this);
  }

  componentDidMount() {
    this.getPatientList();
  }

  render() {
    return (
      <Navbar>
        <div className="col-sm-12 mt-4">
          <h4>My Patients</h4>
          <div className="mt-4">
            <table className="table" this="table">
              <thead>
                <tr>
                  <th scope="col" className="text-left">
                    Name
                  </th>
                  <th scope="col" className="text-center">
                    Number
                  </th>
                  <th scope="col" className="text-right">
                    Profile
                  </th>
                </tr>
              </thead>
              {this.state.patients.map((patient) => (
                <PatientEntry key={this.state.patients.indexOf(patient)}>
                  {patient}
                </PatientEntry>
              ))}
            </table>
          </div>
        </div>
      </Navbar>
    );
  }

  getPatientList() {
    api.getPatients().then((json) => {
      this.setState({ patients: json });
    });
    //dummy data
    this.setState({
      patients: [
        {
          id: 1,
          name: "Majed Nuss",
          number: "123",
        },
        {
          id: 1,
          name: "Majed Nuss",
          number: "123",
        },
        {
          id: 1,
          name: "Majed Nuss",
          number: "123",
        },
      ],
    });
  }
}
export default PatientList;

class PatientEntry extends Component {
  constructor(props) {
    super(props);
    this.state = {
      patient: this.props.children,
    };
  }
  render() {
    return (
      <tbody>
        <tr>
          <td className="text-left">{this.state.patient.name}</td>
          <td className="text-center">{this.state.patient.number}</td>
          <td className="text-right">
            <Link
              to="/patient"
              patientId={this.state.number}
              className="btn btn-primary"
            >
              Profile
            </Link>
          </td>
        </tr>
      </tbody>
    );
  }
}
